apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  namespace: store
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data" # - for Unix/Linux
    #    path: "/run/desktop/mnt/host/c/temp/testfiles" for windows
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: store
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: store
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper
          imagePullPolicy: IfNotPresent
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: zookeeper-persistent-storage
              mountPath: /var/lib/zookeeper
      volumes:
        - name: zookeeper-persistent-storage
          persistentVolumeClaim:
            claimName: zookeeper-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: store
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
