server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000
          jwk-set-uri: http://localhost:8000/oauth2/jwks

logging:
  level:
    org:
      springframework:
        security:
          oauth2:
            server:
              resource: DEBUG