eureka:
  client:
    register-with-eureka: false

server:
  port: 8090

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - CustomTokenRelay=
      routes:
        - id: email-service-router
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/email/**
        - id: user-service-router
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/user/**
        - id: registration-service-router
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/register/**
        - id: host-service-router
          uri: http://localhost:8094
          predicates:
            - Path=/api/v1/host/**
        - id: event-service-router
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/event/**
        - id: payment-service-router
          uri: http://localhost:8096
          predicates:
            - Path=/api/v1/payment/**
        - id: react-app
          uri: http://localhost:3000/
          predicates:
            - Path=/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: client
            client-secret: secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/login/oauth2/code/gateway
        provider:
          spring:
            issuer-uri: http://localhost:9000

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0