server:
  port: 8090

spring:
  application:
    name: cloudgateway
  cloud:
    gateway:
      default-filters:
        - CustomTokenRelay=
      routes:
        - id: email-service-router
          uri: http://localhost:8091/
          predicates:
            - Path=/email-service/**
        - id: user-service-router
          uri: http://localhost:8092/api/v1
          predicates:
            - Path=/user-service/**
        - id: react-app
          uri: http://localhost:3000/
          predicates:
            - Path=/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000" # Include the scheme (http://)
            allowedMethods: "*"
            allowedHeaders: "*"
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: client
            client-secret: secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/login/oauth2/code/gateway
        provider:
          spring:
            issuer-uri: http://localhost:9000
