apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authorization-server
  labels:
    app: authorization-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-server
  serviceName: authorization-server-svc
  template:
    metadata:
      labels:
        app: authorization-server
    spec:
      containers:
        - name: authorization-server
          image: samal024/authorization-server
          ports:
            - containerPort: 9000
          env:
            - name: PROFILE
              value: prod
            - name: DB_MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: mysql_db_url
            - name: DB_MYSQL_USERNAME
              value: "root"
            - name: DB_MYSQL_PASSWORD
              value: "root"
            - name: KAFKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: kafka_server_url
            - name: API_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: api_gateway_url
            - name: ZIPKIN_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: zipkin_server_url
          volumeMounts:
            - name: auth-persistent-storage
              mountPath: /var/lib/auth
      volumes:
        - name: auth-persistent-storage
          persistentVolumeClaim:
            claimName: auth-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: authorization-server-svc
spec:
  clusterIP: None
  selector:
    app: authorization-server
  ports:
    - port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: authorization-server-lb
spec:
  type: LoadBalancer
  selector:
    app: authorization-server
  ports:
    - port: 9000
      targetPort: 9000
