apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-dep
  labels:
    app: authorization-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service-app
    template:
      metadata:
        labels:
          app: chat-service-app
      spec:
        containers:
        - name: chat-service-app
          image: samal024/chat-service
          ports:
          - containerPort: 8097
          env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: config-cm
                key: config_url

---

apiVersion: v1
kind: Service
metadata:
  name: chat-service-svc
spec:
  selector:
    app: chat-service-app
  ports:
    - port: 80
      targetPort: 8097
