apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://config-server-svc"

#---
#
#apiVersion: v1
#kind: Config
#metadata:
#  name: auth-cm
#data:
#  mysql_db_url: mysql
#  kafka_server_url: kafka-server-svc
#  api_gateway_url: "http://127.0.0.1:8090"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-cm
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS orderdb;
    CREATE DATABASE IF NOT EXISTS paymentdb;
    CREATE DATABASE IF NOT EXISTS productdb;
