apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server-app
          image: samal024/config-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: AUTHORIZATION_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-cm

---

apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  selector:
    app: config-server
  ports:
    - port: 8088
      targetPort: 8088