apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://config-server-svc:8088"
  eureka_server_url: "eureka-0.eureka"
  zipkin_server_url: "zipkin-svc"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_service_address: "http://eureka-0.eureka:8761/eureka"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-cm
data:
  mysql_db_url: "mysql-0.mysql"
  kafka_server_url: "kafka-0.kafka-svc"
  api_gateway_url: "api-gateway-0.api-gateway-svc"
  eureka_server_url: "eureka-0.eureka"
  zipkin_server_url: "zipkin-svc"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-cm
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS user_details;
    CREATE DATABASE IF NOT EXISTS event_details;
    CREATE DATABASE IF NOT EXISTS host_details;
    CREATE DATABASE IF NOT EXISTS payment_details;
    CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
    GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
data:
  zookeeper_connect_url: "zookeeper-svc.default:2181"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-init-cm
data:
  server.properties: |  
    listeners=PLAINTEXT://:9092
    advertised.listeners=PLAINTEXT://kafka-broker:9092

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-cm
data:
  email_service_url: email-service-svc
  user_service_url: user-service-svc
  host_service_url: host-service-svc
  event_service_url: event-service-svc
  payment_service_url: payment-service-svc
  chat_service_url: chat-service-svc
  react_app_url: react-app-svc
  authorization_server_url: "authorization-server-0.authorization-server-svc"
  api_gateway_url: "api-gateway-0.api-gateway-svc"
  eureka_server_url: "eureka-0.eureka"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-cm
data:
  eureka_server_url: "eureka-0.eureka"
  mysql_db_url: "mysql-0.mysql"
  kafka_server_url: "kafka-0.kafka-svc"
  config_url: "config-server-svc"
  authorization_server_url: "authorization-server-0.authorization-server-svc"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: react-app-cm
data:
  VITE_API_GATEWAY_BASE_URI : "http://api-gateway-0.api-gateway-svc:8090"
  VITE_EMAIL_SERVICE_BASE_URI : "http://api-gateway-0.api-gateway-svc:8090/api/v1/email"
  VITE_USER_SERVICE_BASE_URI : "http://api-gateway-0.api-gateway-svc:8090/api/v1/user"
  VITE_REGISTRATION_SERVICE_BASE_URI : "http://api-gateway-0.api-gateway-svc:8090/api/v1/register"
  VITE_HOST_SERVICE_BASE_URI : "http://api-gateway-0.api-gateway-svc:8090/api/v1/host"
  VITE_PAYMENT_SERVICE_BASE_URI : "http://api-gateway-0.api-gateway-svc:8090/api/v1/payment"
  VITE_EVENT_SERVICE_BASE_URI : "http://api-gateway-0.api-gateway-svc:8090/api/v1/event"
  VITE_CHAT_SERVICE_BASE_URI : "http://api-gateway-0.api-gateway-svc:8090/api/v1/chat"
  VITE_LOGIN_URI : "http://api-gateway-0.api-gateway-svc:8090/oauth2/authorization/gateway"
  VITE_LOGOUT_URI : "http://api-gateway-0.api-gateway-svc:8090/logout"
  VITE_STRIPE_PUBLIC_KEY : "pk_test_51OltLySBmWDDzEvOmsoOAIXcGc4A17IjT6FjEHSyZV915ZdahaSgMw793UMhv9F2r6JMTIVtWbiqjesLDRtDh2uP0046E7LbWK"
