---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
  namespace: store
data:
  zookeeper_connect_url: "zookeeper-svc.store:2181"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-init-cm
  namespace: store
data:
  server.properties: |
    listeners=PLAINTEXT://:9092
    advertised.listeners=PLAINTEXT://kafka-broker:9092

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-cm
  namespace: store
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS user_details;
    CREATE DATABASE IF NOT EXISTS event_details;
    CREATE DATABASE IF NOT EXISTS host_details;
    CREATE DATABASE IF NOT EXISTS payment_details;
    CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
    GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
  namespace: micro-services
data:
  config_url: "http://config-server-svc.micro-services:8088"
  eureka_server_url: "eureka-0.eureka.micro-services"
  zipkin_server_url: "zipkin-svc.micro-services"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-cm
  namespace: authorization
data:
  mysql_db_url: "mysql-0.mysql.store"
  kafka_server_url: "kafka-0.kafka-svc.store"
#  api_gateway_url: "api-gateway-lb.micro-services.svc.cluster.local"
  api_gateway_url: "http://crowdcraft.site"
  eureka_server_url: "eureka-0.eureka.micro-services"
  zipkin_server_url: "zipkin-svc.micro-services"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-cm
  namespace: micro-services
data:
  email_service_url: email-service-svc
  user_service_url: user-service-svc
  host_service_url: host-service-svc
  event_service_url: event-service-svc
  payment_service_url: payment-service-svc
  chat_service_url: chat-service-svc
  react_app_url: "react-app-svc.micro-services"
#  authorization_server_url: "authorization-server-lb.authorization.svc.cluster.local"
  authorization_server_url: "http://auth.crowdcraft.site"
  #just now changed from authorization-server-0.authorization-server-svc.default
#  api_gateway_url: "api-gateway-0.api-gateway-svc.micro-services.svc.cluster.local"
  api_gateway_url: "http://crowdcraft.site"
  #  api_gateway_url: "api-gateway-0.api-gateway-svc.default"
  eureka_server_url: "eureka-0.eureka.micro-services"
  zipkin_server_url: "zipkin-svc.micro-services"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: react-app-cm
  namespace: micro-services
data:
  VITE_API_GATEWAY_BASE_URI : "http://crowdcraft.site"
  VITE_EMAIL_SERVICE_BASE_URI : "http://crowdcraft.site/api/v1/email"
  VITE_USER_SERVICE_BASE_URI : "http://crowdcraft.site/api/v1/user"
  VITE_REGISTRATION_SERVICE_BASE_URI : "http://crowdcraft.site/api/v1/register"
  VITE_HOST_SERVICE_BASE_URI : "http://crowdcraft.site/api/v1/host"
  VITE_PAYMENT_SERVICE_BASE_URI : "http://crowdcraft.site/api/v1/payment"
  VITE_EVENT_SERVICE_BASE_URI : "http://crowdcraft.site/api/v1/event"
  VITE_CHAT_SERVICE_BASE_URI : "http://crowdcraft.site/api/v1/chat"
  VITE_LOGIN_URI : "http://crowdcraft.site/oauth2/authorization/gateway"
  VITE_LOGOUT_URI : "http://crowdcraft.site/logout"
  VITE_STRIPE_PUBLIC_KEY : "pk_test_51OltLySBmWDDzEvOmsoOAIXcGc4A17IjT6FjEHSyZV915ZdahaSgMw793UMhv9F2r6JMTIVtWbiqjesLDRtDh2uP0046E7LbWK"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-cm
  namespace: micro-services
data:
  eureka_server_url: "eureka-0.eureka.micro-services"
  mysql_db_url: "mysql-0.mysql.store"
  kafka_server_url: "kafka-0.kafka-svc.store"
  config_url: "config-server-svc.micro-services"
  authorization_server_url: "http://auth.crowdcraft.site"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: host-service-cm
  namespace: micro-services
data:
  eureka_server_url: "eureka-0.eureka.micro-services"
  mysql_db_url: "mysql-0.mysql.store"
  kafka_server_url: "kafka-0.kafka-svc.store"
  config_url: "config-server-svc.micro-services"
  authorization_server_url: "http://auth.crowdcraft.site"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-cm
  namespace: micro-services
data:
  eureka_server_url: "eureka-0.eureka.micro-services"
  mongo_db_url: "mongo-0.mongo-svc.store"
  kafka_server_url: "kafka-0.kafka-svc.store"
  config_url: "config-server-svc.micro-services"
  authorization_server_url: "http://auth.crowdcraft.site"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service-cm
  namespace: micro-services
data:
  eureka_server_url: "eureka-0.eureka.micro-services"
  mysql_db_url: "mysql-0.mysql.store"
  kafka_server_url: "kafka-0.kafka-svc.store"
  config_url: "config-server-svc.micro-services"
  authorization_server_url: "http://auth.crowdcraft.site"

---