---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
  namespace: store
data:
  zookeeper_connect_url: "zookeeper-svc.store:2181"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-init-cm
  namespace: store
data:
  server.properties: |
    listeners=PLAINTEXT://:9092
    advertised.listeners=PLAINTEXT://kafka-broker:9092

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-cm
  namespace: store
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS user_details;
    CREATE DATABASE IF NOT EXISTS event_details;
    CREATE DATABASE IF NOT EXISTS host_details;
    CREATE DATABASE IF NOT EXISTS payment_details;
    CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
    GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
  namespace: micro-services
data:
  config_url: "http://config-server-svc.micro-services:8088"
  eureka_server_url: "eureka-0.eureka.micro-services"
  zipkin_server_url: "zipkin-svc.micro-services"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-cm
  namespace: authorization
data:
  mysql_db_url: "mysql-0.mysql.store"
  kafka_server_url: "kafka-0.kafka-svc.store"
  api_gateway_url: "api-gateway-lb.micro-services.svc.cluster.local"
  eureka_server_url: "eureka-0.eureka.micro-services"
  zipkin_server_url: "zipkin-svc.micro-services"

