apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-domain-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: crowdcraft.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway-lb
                port:
                  number: 80
    - host: auth.crowdcraft.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-server-svc
                port:
                  number: 9000
