spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  datasource:
    url: jdbc:mysql://localhost:3306/payment_details
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8088

server:
  port: 8096

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  base-url: http://127.0.0.1:8090

stripe:
  api-key: ${api_key}