spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER_URL}
  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:3306/payment_details
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://${CONFIG_SERVER_URL}:8088

server:
  port: 8096

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO

app:
  base-url: ${GATEWAY_URL}

stripe:
  api-key: ${STRIPE_SECRET_KEY}