server:
  port: 8093

spring:
  application:
    name: registration-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  datasource:
    url: jdbc:mysql://localhost:3306/user_details
    username: root
    password: samal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: TRACE

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0
