spring:
  application:
    name: user-service
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTHORIZATION_SERVER_URL}:9000
  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:3306/user_details
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://${CONFIG_SERVER_URL}:8088

server:
  port: 8092

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO