spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST:localhost}:3306/user_details
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: ${ KAFKA_SERVER_URL:localhost }:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0

gateway:
  baseURI: ${API_GATEWAY_URL:http://127.0.0.1:8090}
  login-endPoint: ${LOGIN_ENDPOINT:/login/oauth2/code/gateway}
