server:
  port: 9000

spring:
  application:
    name: authorizationserver
  datasource:
    url: jdbc:mysql://localhost:3306/user_details
    username: root
    password: samal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: DEBUG
