server:
  port: 8000

logging:
  level:
    org:
      springframework:
        security:
          oauth2: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_details
    username: root
    password: samal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
