spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: authorization-server
  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:3306/user_details
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER_URL}:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  zipkin:
    base-url: http://${ZIPKIN_SERVER_URL}:9411

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_SERVER_URL}:9411/api/v2/spans

gateway:
  baseURI: ${API_GATEWAY_URL}
  login-endPoint: "/login/oauth2/code/gateway"


