server:
  port: 8097

spring:
  application:
    name: chat-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  data:
    mongodb:
      username: ${ username }
      password: ${ password }
      host: localhost
      port: 27017
      database: chat_app
      logging:
        enabled: true
        level: TRACE
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL}:8088

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
        web: INFO
    com.waves.chatservice: INFO

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

aws:
  bucket:
    name: ${bucket_name}
  region: ${region}
  accessKey: ${access_key}
  secretKey: ${secret_key}