server:
  port: 8088

spring:
  application:
    name: config-server
  profiles:
    active: native

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka
