spring:
  application:
    name: email-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
  mail:
    username: ${email}
    password: ${app_password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:configserver:http://localhost:8088

server:
  port: 8091

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
