apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: micro-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: samal024/email-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          env:
            - name: PROFILE
              value: prod
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: email-service-cm
                  key: kafka_server_url
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: email-service-cm
                  key: config_url
            - name: APP_EMAIL_ID
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email_id
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: app_password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8091
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8091
            initialDelaySeconds: 5
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: email-service-svc
  namespace: micro-services
spec:
  selector:
    app: email-service
  ports:
    - port: 8091
      targetPort: 8091


