apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: micro-services
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: samal024/service-registry
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: HOSTNAME
              value: "localhost"
            - name: PROFILE
              value: "prod"

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: micro-services
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
    - port: 8761
      name: eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb-svc
  namespace: micro-services
spec:
  type: LoadBalancer
  selector:
    app: eureka
  ports:
    - port: 8761
      targetPort: 8761
